# Generated by Django 3.1.7 on 2021-03-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treeName', models.CharField(max_length=120)),
                ('rowNum', models.IntegerField()),
                ('treeNum', models.IntegerField()),
                ('treeAge', models.IntegerField()),
                ('treeVariety', models.CharField(max_length=120)),
                ('treeStatus', models.CharField(max_length=120)),
                ('GPS_coordinates', models.CharField(max_length=120)),
            ],
        ),
    ]
